name: My First Workflow

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.MY_AWS_SECRET}}
      - run: echo ${{vars.MY_TEST_VAR}}
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{toJson(secrets)}}
      - run: echo ${{vars}}    
      
        
