name: My First Workflow
on: push

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name : Print Node version
              run : node -v
            - name : Install Node js version 25
              uses : actions/setup-node@v6
              with:
                 node_version : '25'
            - name : Print Node version
              run : node -v
              
