name: My First Workflow

on: 
  push:
    branches: [ main,develop ]

jobs:
  my-prod-job:
    environment: 'PROD'
    runs-on: ubuntu-latest
    steps:
        - run : echo ${{github.ref_name}}

        
